### ISSUE TITLE
JSON embedded functions break the syntax.

### ISSUE THREAD

**Issue by karloluis** [darron/language-ejs#10]
![image](https://cloud.githubusercontent.com/assets/4258614/13314092/7e843554-db79-11e5-823c-39afdd680567.png)

The image shows a `ejs` segment in which a JSON is called with a function. The dot followed by a word followed by a parenthesis (regex `.<w>(`) breaks the syntax functionality until the parenthesis is closed.

**Comment by ciroreed** [comment]
i used to solve this..

**Comment by karloluis** [comment]
I'm guessing you mean you solved it. I see your pull request, now it's a matter of getting the owner @darron to maintain it.

**Comment by ciroreed** [comment]
lol i mean "I need".. sorry.

My PR is about other issue

**Comment by karloluis** [comment]
That's too bad. Let me know if you get it fixed. Looking forward to getting updates on this.

**Comment by ciroreed** [comment]
I found a place where syntax goes well

https://ionicabizau.github.io/ejs-playground/

here is the script.. https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-ejs.js

Im trying to see regular expressions that can fix the language-ejs/grammars/javascript template.cson file

**Comment by karloluis** [comment]
I tried fixing it myself but this is a bit out of my league. Have fun.

**Comment by ciroreed** [comment]
ofc is out of my league too
from https://ionicabizau.github.io/ejs-playground/
@IonicaBizau where you achieve this syntax engine? can you solve this?

**Comment by IonicaBizau** [comment]
Hey guys!

I simply used the [`ejs` mode for Ace Editor](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/ejs.js) there. :grin: 

Truth is that I'm (still) terrible in regex... I don't think I can really help, but maybe that link is useful.

**Comment by ciroreed** [comment]
many thanks! dude!

**Comment by ciroreed** [comment]
Here is useful info to understand this file https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/ejs.js

https://ace.c9.io/#nav=higlighter
